# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "opensuse/Tumbleweed.x86_64"
end

Vagrant.configure("2") do |config|

    config.vm.box = "opensuse/Tumbleweed.x86_64"
    config.vm.hostname = "laboratorio-01"
    config.vm.network :private_network, :ip => "192.168.56.1"
    config.vm.synced_folder "www", "/var/www"

   
    config.vm.provision "shell", path: "instala_pacotes.sh"


    config.vm.provider :virtualbox do |v|
      v.cpus = 1
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "laboratorio-01"]
    end

end
